---
version: "1.0"

services:
  reverse-proxy:
    image: ${REVERSE_PROXY_REPOSITORY}:${REVERSE_PROXY_VERSION}
    container_name: reverse-proxy
    #network_mode: "host" 
    networks:
      auth-network:
        ipv4_address: 172.25.0.10
    ports:
      - ${REVERSE_PROXY_PORT}:8081

    #command: /usr/local/apache2/init/init_index_html.sh
#    depends_on:
#      enterprisesearch:
#        condition: service_healthy
    #environment:
    #  - ENTERPRISE_SEARCH_INTERNAL_URL=${ENTERPISE_SEARCH_INTERNAL_URL}
    #  - ELASTIC_USERNAME=${ELASTIC_USERNAME}
    #  - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    
    volumes:
    #  - ./reverse-proxy-files/config.d/atlas.conf:/usr/local/apache2/conf.d/atlas.conf
      - ./reverse-proxy-files/config.d/atlas2.conf:/usr/local/apache2/conf.d/atlas2.conf
      - ./reverse-proxy-files/config.d/auth.conf:/usr/local/apache2/conf.d/auth.conf
      - ./reverse-proxy-files/config.d/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./reverse-proxy-files/config.d/init_index_html.sh:/usr/local/apache2/init/init_index_html.sh
    #  - ./reverse-proxy-files/config.d/elastic.conf:/usr/local/apache2/conf.d/elastic.conf
    #  - ./reverse-proxy-files/config.d/flink.conf:/usr/local/apache2/conf.d/flink.conf
    #  - ./reverse-proxy-files/config.d/kafka-ui.conf:/usr/local/apache2/conf.d/kafka-ui.conf 


  keycloak:
    image: ${KEYCLOAK_REPOSITORY}:${KEYCLOAK_VERSION}
    container_name: keycloak
    #network_mode: "host" 
    networks:
      auth-network:
        ipv4_address: 172.25.0.11
    ports:
      - ${KEYCLOAK_PORT}:8080

    #command: "nohup /tmp/init_standard_users.sh && /opt/jboss/tools/docker-entrypoint.sh" 
     
    environment:
      - KEYCLOAK_USER=${KEYCLOAK_USER}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
      - PROXY_ADDRESS_FORWARDING=${PROXY_ADDRESS_FORWARDING}
      - KEYCLOAK_IMPORT=${KEYCLOAK_IMPORT}
      - KEYCLOAK_FRONTEND_URL=${KEYCLOAK_FRONTEND_URL}
      - USER_ATLAS_PASSWORD=${USER_ATLAS_PASSWORD}
      - USER_STEWARD_PASSWORD=${USER_STEWARD_PASSWORD}
      - USER_DATA_PASSWORD=${USER_DATA_PASSWORD}
    #  - REDIRECT_SOCKET=${REDIRECT_SOCKET}
    #  - BIND_IP=${BIND_IP}

    volumes:
      - ./keycloak-stack/realm_m4i.json:/tmp/realm_m4i.json    

    #entrypoint: /opt/jboss/tools/docker-entrypoint.sh && /tmp/init_standard_users.sh

  atlas:
    image: ${ATLAS_REPOSITORY}:${ATLAS_VERSION}
    container_name: atlas
    #network_mode: "host"
    networks:
        auth-network:
          ipv4_address: 172.25.0.12
    ports: 
      - ${ATLAS_PORT}:21000
    #  - KAFKA PORT
    
    command: /bin/bash -c /opt/apache-atlas-2.2.0/bin/startup.sh
    environment:
      - ATLAS_EXTERNAL_URL=${ATLAS_EXTERNAL_URL}
      - KEYCLOAK_SERVER_URL=${KEYCLOAK_SERVER_URL}
      - KEYCLOAK_ATLAS_ADMIN_USERNAME=${KEYCLOAK_ATLAS_ADMIN_USERNAME}
      - KEYCLOAK_ATLAS_ADMIN_PASSWORD=${KEYCLOAK_ATLAS_ADMIN_PASSWORD}
    volumes:
      - ./atlas-stack/atlas-application--properties.yaml:/opt/apache-atlas-2.2.0/conf/atlas-application.properties
      - ./atlas-stack/keycloak-conf.json:/opt/apache-atlas-2.2.0/conf/keycloak-conf.json
      - ./atlas-stack/atlas-simple-authz-policy.json:/opt/apache-atlas-2.2.0/conf/atlas-simple-authz-policy.json


volumes:
  reverse-proxy:
    driver: local

networks:
  auth-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1